### ISSUE TITLE
why do u use R2DBC 

### ISSUE THREAD

**Issue by fizz12344321** [aravinth-sivarasa/spring-react-r2dbc-gogo#2]
Hi, i am reading your project and i am interested in this, but i have a question, why do you use R2DBC instead of other non blocking IO like Hibernate Reactive or others... can you tell me your purpose, the pros and cons of R2DBC, thank you so much

**Comment by aravinth-sivarasa** [comment]
Hi, I'm glad you have reviewed my code. Yes, you have a valid point. Since, I'm using spring boot, I don't see any documentation for other reactive apis for the database.  Not only this, I referred  [spring doc](https://spring.io/reactive). Here they mentioned the architecture. In addition when we develop a large-scale application, better to stick with spring managed repository.

I believe, spring boot will adapt the hibernate react API soon.

Hope this will make sense. if you have any suggestions please let me know.
